language: node.js
node.js: -"7" -"8"
install:
- npm install
- npm install --global gulp-cli
- npm install -g bower
- bower install
script:
- gulp
deploy:
  skip_cleanup: true
  email: r567tw@gmail.com
  name: r567tw
  provider: pages
  github_token: "$GITHUB_TOKEN"
  local_dir: "public"
  on:
    branch: master
