language: node.js
node.js: -"7" -"8"
install:
- npm install
- npm install --global gulp-cli
- npm install -g bower
- bower install
before_script:
- git config --global user.email r567tw@gmail.com
- git config --global user.name "r567tw"
- git remote add origin https://r567tw:${GITHUB_TOKEN}@github.com/r567tw/resume.git
script:
- gulp
deploy:
- edge: true
  skip_cleanup: true
  provider: script
  script: gulp deploy
  on:
    branch: master
env:
  global:
    secure: AwcjpxltZIaIUzAq7wbCc19KYokmzTo0Jnt6c52sr1Gj4HYb4IUy8hauG4rN2CO9U04j8xbLCy7MOT9e3gwMcy8i96B/Z2yjyl3OB3tbn3z8kpD/qdgp7zCoKI/Lvu7zCu1xVooeXMnpXBV2kvA1bv3iJoLGt3dKUyeMXhKhoEbFQlkpNKaBO26BG6+xNoPbiB6RJOgzFVdfL8Jf3mesW5PlPJ73gcLm9XfIc7H4dLjI2MLDPQaluixPL79if4eqPvfQtlc9mwl8bL1KslFp0JhhgZX3XwDi991XkHx85pHy/qtEWjhs2jrTKa9N+5agFecNai29EcgQqD6prtmiSHsZXnPi2vVbgnYXhn/1th7Pd0aHXKlAo9KIYB4lHBn6aQmJ54H6sOe3tpBQ2IENvXr+phl9l+hcQfmLgrBotNYoMudhAFZM2ycxwbEbwXn3yuoaq4b81FZxhhv6/Kp9Y9iifYbERu1v4xP2V9CRKTqmGxLc7xA1WM8+vQtwQI6+ADUXS9Jo14LrJrxHfOonolgJpmm0KpBr9D26CxH0NekIqoq/oRVvzLQf4I7r6sc2uNsDGEQ/QFXw2rgJQBX4ZRpo4SlWQDqhmNBXiopZ4RvQ+ZQvn9+8os+EnEvQPjBAA1l5mcc/6Fm9sT56gMmFzjfp/Uw0G+xPA0g6LvKXJGI=
