language: node.js
node.js: -"7" -"8"
install:
- npm install
- npm install --global gulp-cli
- npm install -g bower
- bower install
before_script:
- git config --global user.email r567tw@gmail.com
- git config --global user.name "r567tw"
- git remote rm origin
- git remote add origin https://r567tw:${GITHUB_TOKEN}@github.com/r567tw/resume.git
script:
- gulp
deploy:
- edge: true
  github_token: 94b1035ee7b72dc33a8a029ce3546ca99a7bcc82
  skip_cleanup: true
  provider: script 
  script: gulp deploy
  on:
    branch: master
env:
  global:
    secure: "oSwGNaMkMT+Xf2NOtgdAEt/xgVV/zkpWsndlwKeq2MDAv0dXt/1TYeissjTKQ4VFb41i7TM4ZgOXsdCpam6ZuPOMDu89H0lpiDlzbrzerKz+t5+ed4j6nIj7CJloNVGHsg5DOXmI7c2wJeH5z46Q+pjVsMwHS6cYMjCsqTIUikQ9Oy0F0nw9pFICQjB8yIzwdxb6kBQD81YDDJLFmEfhn6w8BnUcOIZUJu0Ejiel1x8L/9aZBL7/33FxLcY4NkkZev7LITPykOnKZMlHcxcvAltpmYgLdpsMes4Wd7RzWLzPUgaEtwC1Jfu5GEz8FoM0P9JvjWNMhuJqD26BDVuPYITrq8DqwsXEPoDOToNUoJJpbqkxPQ7enTdfPsejZ95W4GhxgyYXyFAMrtg6/FobrNv6phO9HJbY4ZsufuMXY+ZvZuD/JqVyVItlNFrhzVtlPSuBmIn5fAGR9u34I6J7bW8NPvDaiYgPsTI+zdtsbHAYH0x6F4YLbAW2S50dGL4DNIZxgLz6BngbKq5emsMAviVqD24AfythUqStYuF8LrrYlR8+ldnQjKEc2vpicL5gsSI/e48rbsgY9u/PK4QpUF/CMyWzAhgwKFMtz4VNqFD5CYTgEFOIM+IgB1CjOx3P5OsHzJ9N94RlWknBztEhzEXVnLdM2mnVJHTenaABoD8="
