language: node.js
node.js: -"7" -"8"
install:
- npm install
- npm install --global gulp-cli
- npm install -g bower
- bower install
before_script:
- git config --global user.email r567tw@gmail.com
- git config --global user.name "r567tw"
- git remote rm origin
- git remote add origin https://r567tw:${GITHUB_TOKEN}@github.com/r567tw/resume.git
script:
- gulp
deploy:
- edge: true
  skip_cleanup: true
  provider: script
  script: gulp deploy
  on:
    branch: master
env:
  global:
    secure: AbNAzdcWsOtKW1dNNEnLSonjlfhmthPi7/cJ4zD9gCSmNrlXdwvheMf7nXYhXVxJ7gBKdApj8bZ+kknQZoyk+MKnkCqsZAAqvxEKFlcopHj0QIZObhAulXUdEVso16Gb845HneBsgQdHYrtqf0StF1hVMuPiXF4R0BvxCvZp7UbylKU5HdeCda3OiVHHkvrOlB3ZMf6oJvbqTVypz+mQQ+asHdO8niddxVYWgZFrYMlDIrXOYcEzT1dLrW1fcnjDQQr6kJQ1tCHOY9NpqUUxrnVYThjMSeD41FeUrDrD1anzmRwjjb/BVM2OtLv+5NxhNOaQ2BvTE72+EYPJsKXDGkpICXR3n2HU3vx6C4ueYvbcXAQTYOnB/KytwOMYJ1Dr4TsoKaGw8pA6wCgcLzphtkgXEwKVSX3yhQL4Yu9uWyUizIx4mIUwUVQ0HO2FbtH+rdX3525cG1D9zOyv5fDi7RdNEGPWaiLs9XfLW0c9Vd8AQzR18wsuAjAzViKUwRJjHrc6HIMM9w0gbGUtiykH2HByhYRYag7k9ljw/jQGYrWmjrQdJy6FxmZM0eXDvrGiVLavV/n3rQSGJX1KAXauOYlp5OjubM7uDfo6kFFi7LTdpR/tqIth3oiVv9Gfwakqj/T7wmDSOyS5iCfDSBOvdLLUhrMPCysW0jZcjp6HPIc=
