language: node.js
node.js: -"7" -"8"
install:
- npm install
- npm install --global gulp-cli
- npm install -g bower
- bower install
before_script:
- git config --global user.email r567tw@gmail.com
- git config --global user.name "r567tw"
- git remote add origin https://r567tw:${GITHUB_TOKEN}@github.com/r567tw/resume.git
script:
- gulp
deploy:
- edge: true
  skip_cleanup: true
  provider: script
  script: gulp deploy
  on:
    branch: master
env:
  global:
  - secure: jkRk5naThyru1nR8nHyoyoMGdMppbGUPItP04QP17kPrqwf5WTJ4Kf5wj4k7npBXlOrDvzx2CiEpPIlh2CMHl7VPi2uwg0RqBpVf8n8oyNaDrktTKBLhnULx/dWdYzXu4C2Eyrzllfl0DKQfO5+hO4e6owqQ1ZPzmS5Cw9aHGu7dlhejRLCzar23gmau+Hpgj/AnmzMI4ZIdhFfjG8F/RhxlJ8glObMqGxOZK1C89nDWfZrXFI6Q3q85VtmEuOvJduHzsxAK5tmSMckVEu8DOem8utDn4On/ZFpY/e3XGoNXsMOn9b/OZKQe+EcxOncNE7NWgM7d8wxVZehV6mnsQn2i7jtFL/yid/Zjb2ApQ8DiKYTZcTGff/f0PA+PJeZlfCNGcHKiU5ALHuqQiGdq/gOs+sXWLjcbE6VqQRm+ufACo0TMTH253rr5GOhsYGHJkZUlVAOfKCASPPIUc4UQN9HPpjfb9DxZsaFsQ6TwA4SSZPyUYiYQ8W+6nGseBi28gXIeJTRMMHz2yeZaJCwd0Qp9hGYJMv5JIUljKePqkH8NTLaSyZv6cShwvSY4btIK5ynqvSedCF/UIRCYjOhWFJuH3pN9SQNmnqcEBiMq+GtmjUy1X4Oa3zrk4Vxz2PIDRbCJ/i+wc8TbtgUsc8h1MnRRbDRtwHyhxpDlYfX2Pro=
