language: node.js
node.js: -"7" -"8"
install:
- npm install
- npm install --global gulp-cli
- npm install -g bower
- bower install
before_script:
- git config --global user.email r567tw@gmail.com
- git config --global user.name "r567tw"
- git remote rm origin
- git remote add origin git@github.com:r567tw/resume.git
script:
- gulp
deploy:
- edge: true
  skip_cleanup: true
  provider: script
  script: gulp deploy
  on:
    branch: master
env:
  global:
    secure: nmHtsokhaptY/iIXJo0aSj9m2wRU0twfFvcNad0D+uonZ3LrZMAJnRYbkFBJTBOSNWhxrOMgWLv/gb44hmN6Skzdn6R10hKiypfwGsgxK7Suv/r8HQM/0P3nU1Kn0dCkvYb2YWbkSieMWMyQyEZ3/wPJnIkNXHCzYvTh/LVzJrzpgjjBeeYwRdfLzxJO0Gm5J9BkvKzQ1kbqZexww97WVFQ3BhTXAxMUF6BC1MWdUTUt/p9v/PxNeBwWLmyihXC+pQXSJ6G4U52pMx9XC9h+B4D8NvdE+mawRHjtZonH1FhoTJr2Jm+ke2FZvy1zSb/kZhDWaI8FYxwwg3aGOelK9ju4XmB6vaCm0Zv2Ksx8DIwDSpJVwSOLy7+CJLTWAdc8SfFcdbP+YjACO1x2jqUpo0aeHMtjAt7glEJUDJTjJgpHHg/MXiqOTJkPheMO0oWhrtIwuXUggzxraoPpSF2tnPz0GL2qTaXBMjV6vYqm1mIrUx0xRBzjTeTT6XOrxOAJpkDW9JXRahxyOKmCrhMqyDpDfQQ4BScT511ZLhYB3Qp3eNKR9VOUEt6r/NJHypATWy1G77/Z6NsEsuOpIuxghJ1s7JQ++53WsNWkYlHn1sb9o6N5J4ZM8WUFcwvgYNUQLtuZGdVMoEEcu0T5yGWLEYb1gUehbKWO3hm/WN5OYOk=
