language: node.js
node.js: 14.5
install:
- npm install
- npm install --global gulp-cli@2.2.0
- npm install -g bower@1.8.2
- bower install
script:
- gulp
deploy:
  skip_cleanup: true
  email: r567tw@gmail.com
  name: r567tw
  provider: pages
  github_token: "$GITHUB_TOKEN"
  local_dir: "public"
  on:
    branch: master
env:
  global:
    secure: fxYIUr0mHpGfHeZ295YnQQ/cZVUSxj9BbeW0aYhFR2HQNPZCDF6WrAUqKyRrpNVz/+lxLbrKp82updZPJmjrLQEvB99Tt3qfvBZTBs2MMvwwmmmFRJSbQuBSO8ivlsDfY+qekxfoDdv+j3/b8i4xq2YwO9UFNlT7gJqB+uxRXejJ+9+WzrTht+p93pv1M6OmcPJmtuY/GZt4EcbaTJiRo1WCJdP2b425dj1MLaXzpWveA5IPZDzblYoDdtDS/MAHqnUa4EoCLBwP8XkEnrafJHqGaXtIp7Uo/T1ybSOt0KyNS1DrbOE7p3OGU6Rv0qweWO+OKYX9M6JXCJBTISrKzUCZ/UyrghvYl7chtLrbaXJd5vmpaYKjGNAHvKCc3nwDRp1xiSJf/TE1ewSayFgxs10ReQzlgF9gqN4RoYVvL6v8xtv/QU4E4QcqRECoRJa82HtaU3KefxpPeJ59KmheolL2TaSs3r1Sm+19UZDDyQu0tWGOaOgjVoIyHV2QQdfBxh9I+R68cbpAZM4xNUTgTVuIwDvXuC+azmtL7uc7AnYUvEIHKHu6IXoqyJY2u/5J9W86e1LrdlZ+B08PSejfM3uBSKp1RZ4aAG+0urpNLpBs1IXEzM8HX37MCSasRSNFHVxwhYea3bDZs2YMqyAh6EVZmZZJ/ZRqWrbXzBY/gG4=
