language: node.js
node.js:
  -"7"
  -"8"
install:
  - npm install
  - npm install --global gulp-cli
  - npm install -g bower
  - bower install
script:
  - gulp
  - git config --global user.email "r567tw@gmail.com"
  - git config --global user.name "r567tw"
  - gulp deploy

