language: node.js
node.js: -"7" -"8"
install:
- npm install
- npm install --global gulp-cli
- npm install -g bower
- bower install
before_script:
- git config --global user.email r567tw@gmail.com
- git config --global user.name "r567tw"
- git remote rm origin
- git remote add origin https://r567tw:${GITHUB_TOKEN}@github.com/r567tw/resume.git
script:
- gulp
deploy:
- edge: true
  skip_cleanup: true
  provider: script
  script: gulp deploy
  on:
    branch: master
env:
  global:
    secure: "MUnbUG9R1T8CXVpBuyQyRYdyPDZc5HBdvgH6t5V1ejkOBCGZxkhdayT9tlhrkPKof7AHi+RehmnuQb6S2Wrk1w3MKnVBgzJMwKbC5S7Kc/F4DEIeIFuyNZteU6oB362rR7wjyTONeMc/F6OdF5TrS1ksLoQxM8xexMRAOJxYScdmdLS1U3EKd8FP7DCP07o/bdcDTNrTS2ov4aPp6VaIEsiOnTA+cFkCz7S+Br1eEgcxCss7SLnBqVnidnUQ8MOODQB26rh5aMwBhA+1xraQitD0kiE/CKiLXVvUf9ryUlB1YJg/XTR2cbywgG+WFNLhtLqUBz7+t0FGYnqmuqS7oXV4YFxACSCgZUfoGU708zL/GkCluFG7Ylh2jp5pZICdjUVIsIqAi8GsT1i869dTgcnzVgiyMGWOmnGBGl/igJFBorHw8Nh1nT58Kw1G+Gj1VXXqGzGgU2WSzYah8jUoliWk2oqOuyixvkUUnPvP5Kzqy11/rkPUXaQi1DMDHa0vEg2gho8Sg6ZM+dpJrVAiVTnUj08rI9Cn16d6/qR9P0NDONDu7hQiJDNhGM6PUjryYSdlC7ll6ll2dSj8S6DdXUOXaLU/lBR1Q48Z/plhcms5ilmODrdFB5BEvhHTCsPCq/YkSp23q5zHJKYKkmSaziKl0EFV5qShF97BZOMbEr0="
